Upgrade to time 0.3
Binary sizes actually shrink compared to master, so
this is strictly an improvement ;)

Binary sizes with time: 0.3: 798KB
Binary sizes with master (using chrono): 816KB

Also this corrects the TIMESTAMP_FORMAT to work with time instead of chrono.

This is specific error caused by the old value of TIMESTAMP_FORMAT ("%b %d %H:%M:%S%.3f"):
> thread '' panicked at 'Invalid specifier .', /Users/techcable/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.27/src/format/parse_items.rs:11:21

when doing `cargo run --example "full-color"`